from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd6446b7fd193'
down_revision = '1789d17004dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('name', sa.VARCHAR(length=255),
                                     autoincrement=False, nullable=True))
    # ### end Alembic commands ###
