"""rm_data

Revision ID: 7b0577f46d91
Revises: 6723aab504cd
Create Date: 2021-10-21 16:28:12.436649

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '7b0577f46d91'
down_revision = '6723aab504cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("DELETE FROM stats where slug = 'FAGGOTER'")


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
