"""is_voice_trigger

Revision ID: 6723aab504cd
Revises: 107f6798265c
Create Date: 2021-10-08 03:25:52.390159

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6723aab504cd'
down_revision = '107f6798265c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats',
                  sa.Column('is_voice_trigger', sa.Boolean(), nullable=True))
    op.execute("UPDATE chats SET is_voice_trigger = false")
    op.alter_column('chats', 'is_voice_trigger', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_voice_trigger')
    # ### end Alembic commands ###
