"""Chat column

Revision ID: 62c624a5b92e
Revises: d6446b7fd193
Create Date: 2021-09-26 23:16:12.171050

"""
import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62c624a5b92e"
down_revision = "d6446b7fd193"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    new_table = op.create_table(
        "chats",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )

    conn = op.get_bind()
    res = conn.execute("select distinct chat_id from stats")
    results = res.fetchall()

    old_info = [
        {
            "chat_id": r[0],
            "name": "UNKNOWN",
            "is_active": True,
            "updated_at": datetime.datetime.now(),
            "created_at": datetime.datetime.now(),
        }
        for r in results
    ]

    op.bulk_insert(new_table, old_info)

    op.create_foreign_key(None, "local_memes", "chats", ["chat_id"], ["chat_id"])
    op.alter_column("stats", "chat_id", existing_type=sa.BIGINT(), nullable=False)
    op.create_foreign_key(None, "stats", "chats", ["chat_id"], ["chat_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stats", type_="foreignkey")
    op.alter_column("stats", "chat_id", existing_type=sa.BIGINT(), nullable=True)
    op.drop_constraint(None, "local_memes", type_="foreignkey")
    op.drop_table("chats")
    # ### end Alembic commands ###
