"""add member id

Revision ID: 54869121a43f
Revises: 0e3862254181
Create Date: 2021-10-01 20:46:30.069659

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '54869121a43f'
down_revision = '0e3862254181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members',
                  sa.Column(
                      'member_id',
                      sa.BigInteger(),
                      nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'member_id')
    # ### end Alembic commands ###
