"""AnswerChance to AnswerPack

Revision ID: ac0ddfd4a498
Revises: ee9254968037
Create Date: 2022-11-19 04:07:36.729307

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ac0ddfd4a498"
down_revision = "ee9254968037"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answer_packs", sa.Column("answer_chance", sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer_packs", "answer_chance")
    # ### end Alembic commands ###
