"""Delete useless fields in chats table

Revision ID: c66e07266c1f
Revises: 5c9210cbff04
Create Date: 2022-12-24 11:01:08.148221

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c66e07266c1f"
down_revision = "5c9210cbff04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "is_edited_trigger")
    op.drop_column("chats", "is_voice_trigger")
    op.drop_column("chats", "answer_chance")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("answer_chance", sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column("chats", sa.Column("is_voice_trigger", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("chats", sa.Column("is_edited_trigger", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
