"""AnswerEntities to AnswerPacks

Revision ID: f31e1b0a3dc7
Revises: 631b6e233806
Create Date: 2022-11-02 00:22:33.573651

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f31e1b0a3dc7"
down_revision = "631b6e233806"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gif_entities", sa.Column("pack_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "gif_entities", "answer_packs", ["pack_id"], ["id"], ondelete="CASCADE")
    op.add_column("photo_entities", sa.Column("pack_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "photo_entities", "answer_packs", ["pack_id"], ["id"], ondelete="CASCADE")
    op.add_column("sticker_entities", sa.Column("pack_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "sticker_entities", "answer_packs", ["pack_id"], ["id"], ondelete="CASCADE")
    op.add_column("text_entities", sa.Column("pack_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "text_entities", "answer_packs", ["pack_id"], ["id"], ondelete="CASCADE")
    op.add_column("voice_entities", sa.Column("pack_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "voice_entities", "answer_packs", ["pack_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "voice_entities", type_="foreignkey")
    op.drop_column("voice_entities", "pack_id")
    op.drop_constraint(None, "text_entities", type_="foreignkey")
    op.drop_column("text_entities", "pack_id")
    op.drop_constraint(None, "sticker_entities", type_="foreignkey")
    op.drop_column("sticker_entities", "pack_id")
    op.drop_constraint(None, "photo_entities", type_="foreignkey")
    op.drop_column("photo_entities", "pack_id")
    op.drop_constraint(None, "gif_entities", type_="foreignkey")
    op.drop_column("gif_entities", "pack_id")
    # ### end Alembic commands ###
