"""add chance to answer

Revision ID: 8f91b5211c28
Revises: 7b0577f46d91
Create Date: 2022-05-04 19:25:16.433813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f91b5211c28'
down_revision = '7b0577f46d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('answer_chance', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE chats SET answer_chance = 100")
    op.alter_column('chats', 'answer_chance', nullable=False)
    op.drop_constraint('stats_member_id_fkey', 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key('stats_member_id_fkey', 'stats', 'members', ['member_id'], ['id'])
    op.drop_column('chats', 'answer_chance')
    # ### end Alembic commands ###
