"""Denormalize entities

Revision ID: f6f10d508983
Revises: 09a1f6973cfe
Create Date: 2022-12-20 01:33:02.125029

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "f6f10d508983"
down_revision = "09a1f6973cfe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer_entities",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "reaction_type",
            ENUM("TRIGGER", "SUBSTRING", name="answerentitytypesenum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "content_type",
            ENUM(
                "TEXT",
                "VOICE",
                "PICTURE",
                "ANIMATION",
                "VIDEO",
                "VIDEO_NOTE",
                "STICKER",
                name="answerentitycontenttypesenum",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pack_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["pack_id"], ["answer_packs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answer_entities")
    # ### end Alembic commands ###
