"""add data_photo

Revision ID: 16c2968d56fd
Revises: 379fd0a9186b
Create Date: 2022-06-18 20:01:54.518365

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16c2968d56fd"
down_revision = "379fd0a9186b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("local_memes", sa.Column("data_photo", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("local_memes", "data_photo")
    # ### end Alembic commands ###
