"""add data_sticker field

Revision ID: a447984ded8d
Revises: 16c2968d56fd
Create Date: 2022-06-20 00:39:18.250255

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a447984ded8d"
down_revision = "16c2968d56fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("local_memes", sa.Column("data_sticker", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("local_memes", "data_sticker")
    # ### end Alembic commands ###
