"""Nullable false to member_id

Revision ID: 5c9210cbff04
Revises: zx2082b0765e
Create Date: 2022-12-23 12:10:26.058691

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c9210cbff04"
down_revision = "zx2082b0765e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("members", "member_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("members", "member_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###
