"""Description for PhotoEntity

Revision ID: ee9254968037
Revises: f31e1b0a3dc7
Create Date: 2022-11-16 02:11:49.882971

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee9254968037'
down_revision = 'f31e1b0a3dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_entities', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_entities', 'description')
    # ### end Alembic commands ###
