"""VideoEntity and VideoNoteEntity

Revision ID: a0dcf3970818
Revises: ac0ddfd4a498
Create Date: 2022-11-23 01:49:04.455967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'a0dcf3970818'
down_revision = 'ac0ddfd4a498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_entities',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('reaction_type', postgresql.ENUM('TRIGGER', 'SUBSTRING', name='answerentitytypesenum', create_type=False),
              nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['answer_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_note_entities',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('reaction_type', postgresql.ENUM('TRIGGER', 'SUBSTRING', name='answerentitytypesenum', create_type=False),
              nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['answer_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_note_entities')
    op.drop_table('video_entities')
    # ### end Alembic commands ###
