"""Dictionary_entity

Revision ID: e2e56e2fe1a4
Revises: c66e07266c1f
Create Date: 2023-03-09 03:01:53.217699

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e2e56e2fe1a4"
down_revision = "c66e07266c1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dictionary_entities",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dictionary_entities")
    # ### end Alembic commands ###
