"""Morph_answer_chance

Revision ID: 0fb0f6b627b2
Revises: e2e56e2fe1a4
Create Date: 2023-04-26 00:09:41.997134

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0fb0f6b627b2"
down_revision = "e2e56e2fe1a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("morph_answer_chance", sa.SmallInteger(), nullable=True))
    op.execute("UPDATE chats SET morph_answer_chance = 25")
    op.alter_column("chats", "morph_answer_chance", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "morph_answer_chance")
    # ### end Alembic commands ###
