from bread_bot.common.models.answer_entities.gif_answer_entities import GifEntity
from bread_bot.common.models.answer_entities.photo_answer_entities import PhotoEntity
from bread_bot.common.models.answer_entities.sticker_answer_entities import StickerEntity
from bread_bot.common.models.answer_entities.text_answer_entities import TextEntity
from bread_bot.common.models.answer_entities.voice_answer_entities import VoiceEntity
from bread_bot.common.models.answer_entities.video_answer_entities import VideoEntity
from bread_bot.common.models.answer_entities.video_note_answer_entities import VideoNoteEntity
from bread_bot.common.models.answer_entities.answer_entities import AnswerEntity
