FROM python:3.10.5

WORKDIR /code

COPY . /code/

RUN pip install --no-cache-dir --upgrade -r /code/requirements/requirements.txt && \
 pip install --no-cache-dir --upgrade -r /code/requirements/requirements.txt