FROM python:3.9.4

WORKDIR /code

COPY . /code/

RUN pip install --no-cache-dir --upgrade -r /code/requirements/requirements.txt && \
 pip install --no-cache-dir --upgrade -r /code/requirements/requirements.txt